### ISSUE TITLE
Duplicates?...

### ISSUE THREAD

**Issue by brandonros** [kelektiv/node-uuid#117]
node-uuid is required in paypal-rest-sdk and called on line 60 in [this](https://github.com/paypal/PayPal-node-SDK/blob/master/lib/client.js) file. For some reason, I'm getting returned the same uuid consecutively. I don't know if it is paypal-rest-sdk, node-uuid, Mac OS X, pm2? I've tried restarting all of my instances. I'm about to console.log the returned UUID.

I get 'e7d48462-0cdb-4291-a4c7-8adeade30193' repeatedly.

**Comment by broofa** [comment]
'Looks like a valid v4 id.

If possible, I would suggest stepping into the uuid.v4() method to see if it's actually generating the same random #'s each time at [this line](https://github.com/broofa/node-uuid/blob/master/uuid.js#L206).  Also, do `_rng.toString()` while stopped in that function to see which logic it's using for random # generation.

**Comment by Misterhex** [comment]
+1, im getting duplicates when i`m calling v4() repeatly

**Comment by tracker1** [comment]
Could it be the compiler is doing a weird optimization having `_rnds` defined outside the function scope?  It may be better to include a more better random number generator as a fallback [1].  It would help to know which random number generator is being used, or at least the full browser/os versions.

[1] https://www.npmjs.com/package/random-js

**Comment by coolaj86** [comment]
Can you guys test this now? It sounds like it may have been related to the recently closed bug where `Math.random()`, which isn't very random, was being used accidentally.

**Comment by FuzzySockets** [comment]
Also getting duplicates when using uuid.v1() as a default mongoose field.

**Comment by antoine-duchenet** [comment]
Also getting duplicates with uuid.v4(), a server restart is required to change the value.
However, I use this library in two projects, and the second one has no duplicates problem, even if the uuid.v4() is used the exact same way.

**Comment by raditha** [comment]
+1 Is there a fix for the duplicate ids?

**Comment by broofa** [comment]
Haven't seen a recipe to reproduce this.  Not enough info to diagnose. Until that changes this isn't actionable.

**Comment by jfdoube** [comment]
Use a docker container or aws lambda, might be easier to reproduce

**Comment by ddellamico** [comment]
We have the exact same issue only running on docker containers... some suggestions ?

**Comment by broofa** [comment]
I'll reopen if/when someone posts a [SCCE](http://sscce.org/) test case.  Better still, identify a fix and submit a PR.

(My  apologies but I simply don't have time to chase this down based on the vague descriptions given so far.)

**Comment by FuzzySockets** [comment]
Refer to antoine-duchenet's post above.  If you call the function directly as a property value (for example) without forcing it to evaluate fresh at run-time, you'll just end up with a static value. Hard to say that's the issue everyone is experiencing, but in my case it was the solution.

`` export { myProperty: uuid.v4() } `` vs `` export { myProperty: () => uuid.v4() } ``

**Comment by broofa** [comment]
@FuzzySockets: I'm confused.  What you're describing is exactly what I would expect.  The first case is just assigning the result of `uuid.v4()` to `myProperty`.  Why would you expect anything other than a static uuid value there?

```
> const before = { myProperty: uuid.v4() }
undefined
> before.myProperty
'bdf9794f-0897-48dd-8fed-da380dac6e74'

> const after = { myProperty: () => uuid.v4() }
{ myProperty: [Function: myProperty] }
> after.myProperty
[Function: myProperty]
> after.myProperty()
'40848bdb-7c04-40e2-8694-5513db705732'
> after.myProperty()
'd1edd511-6ce9-4a12-b196-4fafb6b3b16f'
> after.myProperty()
'1258559b-c082-436c-8ecb-f74679954ffd'
> // Etc ...
```

**Comment by FuzzySockets** [comment]
@broofa At the time I was following along with an example that (incorrectly) showed how to generate unique uuids for a mongoose model. Without having ever used node-uuid before, you might just assume either uuid returns a random generator function vs a static value which is where my error resided, or that mongoose encloses the model object, therefore calling the function each time you instantiate the model.

**Comment by broofa** [comment]
@alkhachatryan: [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Rasfuranku** [comment]
I have an action that will get two unique tasks from an array of ten items. The action is triggered manually. If the same task is selected on different actions the id assigned is repeated. 

```
export const getTasks = (): ITask[] => {
    const selectedTasks = [];
    const tasksCopy: ITask[] = [...tasks];
    
    for (let i = 0; i < 2; i++) {
        const index = randomIndex(tasksCopy.length);
        const task = tasksCopy.splice(index, 1);
        const id = uuidv4();
        task[0].id = id;
        task[0].status = TaskStatus.processing;
        selectedTasks.push(task[0]);
    }

    return selectedTasks;
}
```

**Comment by broofa** [comment]
@Rasfuranku: On the rare occasion we've seen issues with duplicates, it's most often because the runtime involved provides a random-number API (e.g. `crypto.getRandomValues()`) that deliberately returns non-random values.

Provide a [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/minimal-reproducible-example) example] and I'll be happy to take a look.

**Comment by Rasfuranku** [comment]
@broofa I found that I was an idiot, and I was mutating the object before adding it to the array. Thanks for your time.

**Comment by t1maccapp** [comment]
This could happen in Lambda env. More context here: https://stackoverflow.com/questions/65369650/aws-lambda-and-uuid-it-always-return-same-value

**Comment by broofa** [comment]
@t1maccapp: SO question is a result of user error and is not relevant to this project (as is clearly explained by the one and only answer there.)

Locking thread as it's been a while since there was any productive conversation.

## If you're contemplating reporting an issue with `uuid` duplicates...

You're welcome to do so, but please provide a [minimum reproduction](https://minimum-reproduction.wtf/), and double check your work.  It's far more likely the problem is with how this project is used rather than with the project itself.
