### ISSUE TITLE
1.4.4 breaks with Browserify & PhantomJS

### ISSUE THREAD

**Issue by dpogue** [kelektiv/node-uuid#126]
(Originally reported by @heilage-nsk at https://github.com/broofa/node-uuid/issues/124#issuecomment-156103317)

> After last minor upgrade the uuid generation began to fail within browserify on browsers that do not support window.crypto (ie10 and older, opera 12, phantomjs 1.9). Why such breaking change was introduced without changing major version?

This is affecting us too.

See also:
https://github.com/request/request/pull/1897
https://github.com/crypto-browserify/crypto-browserify/issues/143

**Comment by coolaj86** [comment]
Looks like it's a bug in browserify's rng.js then?

For a temporary workaround I'll actually run `rng()` and spit out a warning if console exists and Math.random() is used.

**Comment by calvinmetcalf** [comment]
so it's a bug in phantomjs with a work around possible in browserify

**Comment by coolaj86** [comment]
Please test with v1.4.6.

**Comment by dpogue** [comment]
1.4.6 works. Thanks!

**Comment by heilage-nsk** [comment]
Thank you for quick reply. Unfortunately, v1.4.6 still fails for me in phantomjs 1.9.18 :(
It seems to be an issue with `Buffer` implementation, that causes crypto.getRandomValue to throw a `TYPE_MISMATCH_ERR`. I've found this workaround: https://github.com/feross/buffer/issues/63

When I add it before any _rng calls, it begins to work: `Buffer.TYPED_ARRAY_SUPPORT = true`
But I'm not sure about any conditions for adding or not adding this workaround.

**Comment by sohara** [comment]
We get phantomjs hanging on our test suite with v1.4.6 as well. We're using phantomjs 2.0.0.

**Comment by coolaj86** [comment]
It seems to me that there's almost more lines of hacky code trying to get around these cross-environment and transpiler issues than actual code in the file.

Perhaps what we really need is to somehow specify in the package.json / bower.json / components.json etc "use xyz if you're loading this in a browser or abc if it's in node"...

hmm....

**Comment by calvinmetcalf** [comment]
actually my error was I had a typo in my test and phantomjs wasn't showing it, crypto-browserify/randombytes#3 works in phantomjs

**Comment by coolaj86** [comment]
Alright, 1.4.7 is up for testing. More workaround hacks for more workaround hacks.

**Comment by heilage-nsk** [comment]
Thank you!
I can approve that on 1.4.7 everything runs fine with phantomjs 1.9.18.
