### ISSUE TITLE
Is there a way to setup node environment when window global is present?

### ISSUE THREAD

**Issue by jakubzitny** [kelektiv/node-uuid#134]
Hi, so you are deciding between `browser` or `node` environment based on presence of window variable:

``` js
if (_window) {
  setupBrowser();
} else {
  setupNode();
}
```

where `_window` is

``` js
'undefined' !== typeof window ? window : null
```

We have a `window` global in node though and we would like to have the `node` part with `crypto.randomBytes` available. So we get rid of:

```
[SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()
```

Is there any workaround for this? 
Or are you willing to change the "decision" part for node to be more complex than just `window` being undefined? (e.g. having a `window.iAmStillNode` set to `true` or something more complex)

**Comment by tracker1** [comment]
I usually suggest people use:

```
var w = (typeof window !== undefined && window.self === window) ? window : null;
```

Since window.self is a browser constraint that I haven't seen both implemented in common globals otherwise... and if anyone does, they deserve what they get imho.

**Comment by jakubzitny** [comment]
This looks great, and I agree. :+1:

**Comment by jakubzitny** [comment]
What does @coolaj86 think?

**Comment by jamespedid** [comment]
I'm running into this problem as well.

**Comment by phun-ky** [comment]
I get this problem in the browser, specifically in IE10 (ie edge + chrome + firefox is fine).

**Comment by coolaj86** [comment]
If someone wants to PR I can pull it in.

I'd rather `try { setupNode(); } catch (e) { setupBrowser() }` because depending on `window.self` just sounds like we're gonna land in trouble somehow somewhere.

**Comment by shankiesan** [comment]
FWIW, I'm having this come through as a warning when running tests in Jest.
