### ISSUE TITLE
Failed to compile react-native on macos 

### ISSUE THREAD

**Issue by RezaRahmati** [kelektiv/node-uuid#141]
I get this error on compiling react-native on macos

Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/crypto and its parent directories

event I installed crypto (0.0.3) by npm and still the same

but it compiles fine for android on windows

**Comment by philolo1** [comment]
I have the same issue :(

**Comment by ryanhomer** [comment]
Check your `node_modules` folder to see if you already have a `uuid` folder. Seems like it's part of the standard react native installation but I'm not sure. If you do have it, then try:

```
var uuid = require('uuid');
var myUuid = uuid.v1();
```

**Comment by defunctzombie** [comment]
Project has been combined with `uuid` module project. If issue persists on latest version of `uuid` module please re-open with example and thoughts on how to fix.
