### ISSUE TITLE
Issues with requirejs on electron

### ISSUE THREAD

**Issue by atishay811** [kelektiv/node-uuid#145]
In the electron environment, node-uuid tries to register itself as a node module and breaks in case of it is loaded as AMD.

**Comment by coolaj86** [comment]
See manual rng usage

https://github.com/broofa/node-uuid/blob/master/README.md#uuidv4options--buffer--offset

**Comment by defunctzombie** [comment]
Project has been combined with `uuid` module project. If issue persists on latest version of `uuid` module please re-open with example and thoughts on how to fix.
