### ISSUE TITLE
AMD not supported anymore

### ISSUE THREAD

**Issue by asimen1** [kelektiv/node-uuid#152]
The new version (3.0.0) doesn't support AMD anymore.
Code should be wrapped with 'define' (like was in previous 1.4.7 version).

**Comment by defunctzombie** [comment]
No it shouldn't. If you want a specific type of module bundle, use any number of module bundlers or see the readme for how to use online tools to create a bundle for you.

**Comment by asimen1** [comment]
Sorry, I don't understand... 
I'm using requirejs as my module bundler, it cannot bundle a module that does not have AMD support since there is no 'define' wrapping.

I think it would be preferred to have AMD support out of the box and not use a runtime service like wzrd.in (which is the only option currently).

**Comment by defunctzombie** [comment]
I do not think AMD is worth supporting out of the box, recommend using a
runtime service to create the appropriate file for your needs. Better yet,
recommend using a bundling tool webpack, roll up, browser often, etc.
