### ISSUE TITLE
Using with SystemJS

### ISSUE THREAD

**Issue by danielgerlag** [kelektiv/node-uuid#162]
When using with SystemJS in browser, I get "rb" is not a function error.
Do have have any working examples with SystemJS?

**Comment by defunctzombie** [comment]
we do not

**Comment by danielgerlag** [comment]
Do you have any plans to support systemjs?

**Comment by defunctzombie** [comment]
Nope

**Comment by danielgerlag** [comment]
Guess I will have to drop this library from my project then

**Comment by broofa** [comment]
Your SystemJS setup is ignoring [the `browser` field uuid provides](https://github.com/kelektiv/node-uuid/blob/master/package.json#L21) indicate when to use rng.js vs. rng-browser.js.  See https://github.com/systemjs/systemjs/issues/860#issuecomment-149982732

**Comment by danielgerlag** [comment]
Nope, still doesn't work... The only way I can get it to work is to modify rng-browser.js, and change the last line to 
```Javascript
module.exports = { randomBytes: rng };
```
But still, I'm developing a library myself, and I need something that just works out of the box for the users of my library.

**Comment by broofa** [comment]
If you're getting `rb is not a function`, then you're still loading rng.js rather than rng-browser.js

```bash
kieffer@Roberts-MacBook-Pro$ grep -r --exclude-dir .git "\Wrb\W" .
./lib/rng.js:var rb = require('crypto').randomBytes;
./lib/rng.js:  return rb(16);
```

**Comment by danielgerlag** [comment]
Nope, that was the first error, after patching in rng-browser.js is still does not work because it doesn't return an object with the same signature as the other one

**Comment by broofa** [comment]
Sorry, I don't know what to tell you at this point.  Let us know if you track this down to an actual issue with this module, I guess. :-/
