### ISSUE TITLE
Add prebuilt distros (with browser versions)

### ISSUE THREAD

**Issue by evil-shrike** [kelektiv/node-uuid#164]
As I understand you don't want to add AMD/UMD support into the lib. 
But currently it's unclear how to use it in browser.
There're two different rnd-generators, but one is hardcoded (in require) and another (rng-browser.js) is not used. 
How do you suppose building the browser version?

I'd suggest adding some build task which would create distributive for browser (`/dist/browser`).  
The browser distro would contain a full version file (with all v*.js + rng-browser combined) without any import/require and so on, and a file per algorithm (uuid-vx.js). But again every file will be w/o any dependencies.

And I'd suggest to put all there distros in the repository and update as a new version is released on npm.

**Comment by defunctzombie** [comment]
The readme says how to get a version suitable for browser use. Please read it.
