### ISSUE TITLE
Parse/unparse methods removed in v3??

### ISSUE THREAD

**Issue by danactive** [kelektiv/node-uuid#166]
I missed the reason why parse() and unparse() methods were removed in v3.0.0. Why remove unparse()?

```
uuid.unparse(buffer);    // -> '02a2ce90-1432-11e1-8558-0b488e4fc115' 
uuid.unparse(buffer, 16) // -> '02a31cb0-1432-11e1-8558-0b488e4fc115' 
```

**Comment by defunctzombie** [comment]
To keep this library focused on generating uuids. Unparsing them gets into realm of validation etc and that I have determined to be outside of the scope of this library.

**Comment by vcarel** [comment]
@defunctzombie But how can we generate an UUID string from a buffer ?

From another perspective, if you decide to remove String / Buffer conversion from the scope of the lib, I think uuid.v* should always return the same kind of object. Either a String or a Buffer.

Another lib could do the work of parsing an UUID Buffer into a String and conversely.

**Comment by vcarel** [comment]
Actually I found this one: https://github.com/zefferus/uuid-parse ;-)
