### ISSUE TITLE
TypeScript type definition conflicting on `require`

### ISSUE THREAD

**Issue by BrainCrumbz** [kelektiv/node-uuid#168]
Hello all. We tried installed this dependency, at current v3.0.1, in an Angular 2/ TypeScript 2/ Webpack 2 project. In order to make that build, we also installed type definition from `@types/uuid`, currently v2.0.3.

The build then fails anyway with the following:

> xxxxx\node_modules\@types\node\index.d.ts:73:13
    Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'Require', but here has type 'NodeRequire'.

At a first look, that seems some kind of conflict with another `require`definition. In `package.json` we also have `@types/requirejs`, v2.1.28. Has anyone experienced this same issue using the library in TypeScript?

**EDIT** Our `project.json` does not explicitly include `@types/node`. That comes with `@types/uuid`.

**Comment by blakeembrey** [comment]
@BrainCrumbz This is not an issue of this repo, it's an issue of https://github.com/DefinitelyTyped/DefinitelyTyped. No one here will be able to help you.

**Comment by BrainCrumbz** [comment]
Thanks for hints. Will try that.
