### ISSUE TITLE
Question: How to generate uuid (v4) without the hyphens in most performant way?

### ISSUE THREAD

**Issue by shamasis** [kelektiv/node-uuid#170]
I have a use-case where I need UUIDs in high volume with no hyphens in them. I understand that we can do `uuid().replace(/-/g, '')`. But is that performant enough? The process of replacing after generation also seems wasteful.

**Comment by broofa** [comment]
1.  I'm curious what your use case is where you care about this level of performance.
2. My gut reaction is the performance of `replace()` won't be an issue
3. If it really is an issue, I'm sure there are more performant alternatives to replace.  E.g. `substr()`.

**Comment by mateja176** [comment]
This is [one use case](https://stackoverflow.com/questions/14940660/whats-mongoose-error-cast-to-objectid-failed-for-value-xxx-at-path-id), point to the accepted answer.

**Comment by broofa** [comment]
@mateja176 Mongo DB querying?   As noted above, the perf of `replace()` is almost certainly dwarfed by whatever Mongo is doing to process the query.

**Comment by OctaneInteractive** [comment]
I know this issue is closed, but I have a use case that involves creating temporary tables in MySQL with unique names:

`const nameOfTable = `duplicateExistingJobItems${Packages.uuidv4().toString().replace(/-/g, '')}``

**Comment by broofa** [comment]
@OctaneInteractive et al:  `uuidv4()` should return a string, so the `toString()` is probably not necessary.

FWIW, [`replaceAll()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) is now a thing and probably slightly more performant than `replace()`.  (Note: Requires node 15+)
```
> require('uuid').v4().replaceAll('-', '')
'b2d46dca936942a081c7d8b5e2e62041'
```
