### ISSUE TITLE
browserify --bare cause global is undefined in browser environemnt

### ISSUE THREAD

**Issue by fbuecklers** [kelektiv/node-uuid#172]
Hi,

is there any reason, why rng-browser.js use global explicitly? 
We create a browserify --bare bundle which do not inject the global variable which breaks our browserify bundle. 

Isn't it better to just test crypto availability with typeof and use it directly? Therefore the global access is made implicitly which works well in browser and in node environments.

Thanks!
Florian

**Comment by broofa** [comment]
Fixed in #221
