### ISSUE TITLE
Interested in adding V3?

### ISSUE THREAD

**Issue by nbenns** [kelektiv/node-uuid#174]
I have implemented V3 to convert to UUID from a string (I could convert to buffer) as I required it for a project.

If you interested, I can add it to the project and submit a PR.

**Comment by defunctzombie** [comment]
No personally, but we would look at a well done PR if it doesn't increase the project size a large amount.

@broofa ?

**Comment by broofa** [comment]
I'd be curious to see @nbenns solution.  v3 and v5 support has been on my short list of features to add.  The main reason I've held off on this is a combination of these not being as in-demand, and the need for the requisite hash [md5/sha1] implementations.  This isn't an issue in node, where there are native implementations we can lean on, but outside of that requires a 3rd party solution, and those can be a bit heavy.

One possibility would be to have users inject that dependency.  E.g. `require('uuid/v3').setHashFunction(...)`, although that's kind of ugly.  Or we could just bite the bullet and take on that dependency.  Or, we could ingest it into this module and do something similar to how we handle the rng[_browser] files.

**Comment by nbenns** [comment]
So far my implementation is naive, and uses node-crypto.

I didn't realize this project worked in the browser as well, so that does complicate things... now I realize why there is hesitation in adding V3/V5 to the project.

I think it is obviously important about figuring out whether you want to take on the hash algorithms as part of you're code, or pull them in from another source and take on the dependency.

I don't mind implementing md5 if you don't want to pull in a dependency (should be fun, but might take a while)

Once you have md5, the actual implementation of V3 is dumb simple, and is same for V5 (with SHA1).

**Comment by broofa** [comment]
There numerous JS md5 implementations out there - no need to implement from scratch.  Ditto for sha1.

**Comment by mike-marcacci** [comment]
Has any progress been made here? I'm looking for v5 support in the browser actually, and don't mind implementing it... unless somebody here is already sitting on good code :-)

If not, I'll submit a PR.

**Comment by broofa** [comment]
[PR for v5 support](https://github.com/kelektiv/node-uuid/pull/188).  Check it out and let me know your thoughts.

I know this isn't v3 support, however the RFC actually encourages the use of v5 (sha1) instead of v3 (md5).  Specifically, from [section 4.3](https://tools.ietf.org/html/rfc4122#section-4.3):

> Choose either MD5 [4] or SHA-1 [8] as the hash algorithm; **backward compatibility is not an issue, SHA-1 is preferred**

**Comment by broofa** [comment]
Namespace uuids (v5) added in #188
