### ISSUE TITLE
Provide instructions for usage with babel

### ISSUE THREAD

**Issue by heygrady** [kelektiv/node-uuid#185]
There are issues with how the random number generator code is implemented. It fails with default settings in browserify and babel. (See #172)

There are a number of issue that describe the problem but none that detail the solution.

- There should be notes in the main readme for usage with popular packaging setups, like babel.
- The code should be patched so that it doesn't break by default.

The [offending line](https://github.com/kelektiv/node-uuid/blob/master/lib/rng-browser.js#L7) is relying on `global` being defined as `window`. For some reason `global === undefined` when this library is included in another project and compiled using babel/webpack.

**Comment by dessant** [comment]
I can second this, after commenting out that line, my webpack bundle does not throw this error anymore:
```js
TypeError: modules[moduleId] is undefined[Learn More]  manifest.bundle.js:55:12
```
Defining `global` is also a workaround: https://github.com/webpack/webpack/issues/1887#issuecomment-172344694
