### ISSUE TITLE
node-uuid naming issue

### ISSUE THREAD

**Issue by moogus** [kelektiv/node-uuid#187]
Hi

I use ember at work and the renaming of the install from node-uuid to uuid is making a right mess of the install.  Can you name it back. It's added a minute to the CI.

Thanks Darren

**Comment by broofa** [comment]
Please provide a more detailed explanation for how changing a module name would have any effect on CI timing.  This doesn't make sense to me.

**Comment by moogus** [comment]
Hi

Thanks for the response.  

I've been trying to speed up a travis cI build.  I've resolved all the issues with in the configuration and project, the build seems to hang on the npm install, specifically when installing ember as it is trying to resolve this package but by it's previous name.  I did consider raising a pr against ember with the revised naming but it seems a lot of ember addons also reference the previous naming.  

I've seen the re-naming/depreciation posts. Any suggestions?

**Comment by broofa** [comment]
> Any suggestions?

I'm afraid not.   I'm not familiar enough with ember or travis to offer much help.

Where this project is concerned, there are two packages published in NPM: the old `node-uuid`  (v1.4.X), which is kept around for backward compatibility, and `uuid` (v3.0.1), which is the one being actively maintained.  Both modules are tiny, with zero dependencies, so it's unlikely there's anything intrinsic to them that would cause your CI to hang.  They're also used by 1000's of projects, so changing the name is a non-trivial ask, and not something we're likely to be doing any time soon.

You'll need to track this issue down further and identify a definitive cause related to this project before we move on this, I'm afraid.  Closing for now.  Feel free to report back if/when you figure out what's going on.

**Comment by moogus** [comment]
thanks for explaining
