### ISSUE TITLE
How can I got the UUID without `-`?

### ISSUE THREAD

**Issue by DravenK** [kelektiv/node-uuid#207]
I need the UUID like this `5CC31D610AC1160C4C28744C52C73A96`,what should I do？

**Comment by broofa** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

**Comment by DravenK** [comment]
I got one way to 
```
const uuid = require('uuid/v4');
let hi = uuid().replace(/-/g,'');
```

**Comment by DravenK** [comment]
@broofa thanks

**Comment by anlexN** [comment]
@broofa , in the cli, how to do it ?
