### ISSUE TITLE
when i command  npm install -g firebase-tools

### ISSUE THREAD

**Issue by BasimYH** [kelektiv/node-uuid#212]
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

please hellp me

**Comment by broofa** [comment]
http://npm.anvaka.com/#/view/2d/firebase-tools  shows `universal-analytics` and `request` modules both depend on node-uuid@1.4.8

Convince those projects to upgrade to more recent version of `uuid` and the warning will go away.  That said, warning is harmless and can be ignored.
