### ISSUE TITLE
typos in the readme on NPM

### ISSUE THREAD

**Issue by blord-fullscreen** [kelektiv/node-uuid#214]
These are typos I am assuming? Note that the Github readme doesn't have the first typo (arrow) but does have the second. Confusing for a newcomer.

![this-aint-right](https://user-images.githubusercontent.com/27975206/28344787-bd4b1f26-6bda-11e7-9af3-a99082acd86b.png)

Thanks!

**Comment by Landmaster** [comment]
FIxed in #215, can be closed
