### ISSUE TITLE
Crypto package has been Deprecated

### ISSUE THREAD

**Issue by DavisSylvester** [kelektiv/node-uuid#218]
Having issue installing now that the above package has been Deprecated

**Comment by broofa** [comment]
Unclear issue.  What are you referring to?

**Comment by broofa** [comment]
Closing.  If you'd like me to reopen, please provide enough info/details to make this actionable.

**Comment by kefahB** [comment]
Hi,
I use your plugin in `Nativescript` and when I use my App crash with error and when I try to install `crypto` dependencie I receive npm deprication : 

```sh
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
```
```sh
Could not find module 'crypto'. Computed path '/Library/Developer/CoreSimulator/Devices/3F44049B-5E3A-44F2-85B0-DAF82949BBA5/data/Containers/Bundle/Application/3BF3138D-1ACE-405B-A8D7-EFC50FA7591D/app.app/app/tns_modules/crypto
```

Thnaks

**Comment by broofa** [comment]
@kefahb - That's not an issue with this module. (`uuid` does not have a hard dependency on 3rd-party crypto module.)   Try `npm ls crypto` to see which module(s) are requiring that `crypto@1.0.1`
