### ISSUE TITLE
API method to validate UUIDs

### ISSUE THREAD

**Issue by timkinnane** [kelektiv/node-uuid#230]
I was using the guid package, but they've recommended switching to this one. The one feature difference I was making use of is their `.isGuid(guid)` method, to validate existing or externally supplied UUIDs (in unit tests).

Is it possible to add a something like `.isUUID(uuid, version)` to this API?

**Comment by timkinnane** [comment]
Actually I guess the version wouldn't matter in determining if it's compliant.

**Comment by broofa** [comment]
https://www.npmjs.com/package/uuid-validate
