### ISSUE TITLE
deprecated node-uuid@1.4.7: Use uuid module instead

### ISSUE THREAD

**Issue by MAYDAY1993** [kelektiv/node-uuid#231]
hi, I've read some related issue and my question is as follows:
warning after **npm install** :

![30](https://user-images.githubusercontent.com/14831051/32041447-a8646582-b9f9-11e7-9f0d-6dac056a3639.png)

and I want to know related dependent, but there is no node-uuid's dependent, uuid has some dependent:

![31](https://user-images.githubusercontent.com/14831051/32041450-af3c89ca-b9f9-11e7-99f3-f3b36431ebeb.png)

and I searched in my **package.json** file,there was **no** node-uuid: 
![32](https://user-images.githubusercontent.com/14831051/32041462-b7e8af18-b9f9-11e7-8c58-a37e0a32b42b.png)

so I'm a little bit confused ,I want to deal with this warning message to let it not show any longer,any suggestions? thank you so much 😄

**Comment by broofa** [comment]
Sounds like you're getting the notice about node-uuid being deprecated, but your writeup is a little unclear.  Try `npm ls node-uuid` in your project directory.  That should show any modules that have the deprecated dependency.  You'll need to contact the project owners about updating those projects to use `uuid` instead.

**Comment by MAYDAY1993** [comment]
@broofa  hi, I've already use **npm ls node-uuid** in the second img ,but output was empty, so I'm a little bit confused.
