### ISSUE TITLE
npm warm use deprecated , use uuid module instead

### ISSUE THREAD

**Issue by Jayesh07** [kelektiv/node-uuid#237]
![1](https://user-images.githubusercontent.com/16936520/33159970-8fb9ceb8-d03e-11e7-856e-dba24b59f94f.JPG)
Hello, 

Is their anyone help me out please

**Comment by broofa** [comment]
@anchnk Thanks for helping out with these issues!

**Comment by anchnk** [comment]
@broofa Thanks for your hard work on this module
