### ISSUE TITLE
feature request - typescript support

### ISSUE THREAD

**Issue by ORESoftware** [kelektiv/node-uuid#243]
it would be great for there to be TS support

especially since there are multiple ways to import the library etc.

**Comment by broofa** [comment]
What exactly would that entail?

**Comment by ORESoftware** [comment]
I have converted a lot of projects to TS from JS

1. install tsc => `npm install -g typescript`
2. create a `tsconfig.json` file in the root of the project
3. run tsc => `$ tsc `

Boom your project is now a TypeScript project, but you have to add some types to make it useful.

Also, add "types" / "typings" as a property in your package.json file and make those properties point to the file that exports the types from your project.

**Comment by broofa** [comment]
Have you looked at https://www.npmjs.com/package/@types/uuid ?

I walked through your steps but got bogged down trying to get the config file and package.json file set up properly (I don't have much time/interest in pursuing this at the moment.)  If you'd like to put up a PR detailing what you're after, feel free to do so.  But know that the odds of it being accepted are very low.  I don't see this adding much value here, and the majority of users don't care about TS... so it'd be adding complexity with no real benefit.

Another option that might make more sense would be to do this as a separate module ("uuid-ts"?) for the time being.  If/when it gets enough traction we can look into merging it back in here.

**Comment by ORESoftware** [comment]
I can submit a PR to get it started - TS is a superset of JS so it will always compile and run which is nice.

**Comment by ORESoftware** [comment]
ah yes, maybe `@types/uuid` is good, although I think it's better to include the types in the project itself

**Comment by broofa** [comment]
I'm gonna close this out for now.  If/when you put up a PR, reference it here and I'll reopen if I think it has legs.
