### ISSUE TITLE
Check if a string is a UUID

### ISSUE THREAD

**Issue by light24bulbs** [kelektiv/node-uuid#244]
Does this library have a way to assert that a string is a valid UUID?  That would be super handy for testing, especially because the way you have exposed the dependencies as raw functions makes them harder to stub. The old API  `uuid.v4 ` was easier to stub.

This much less popular uuidv4 library has the ability to check the strings: https://github.com/thenativeweb/uuidv4

I was able to test a uuidv4 generated by your lib with that libs .is() function, so that's a perfectly good workaround, but it would be nice if it was part of your lib.

**Comment by broofa** [comment]
There's already a module for this - https://www.npmjs.com/package/uuid-validate - with download counts (~27K/month) that are 0.1% of this module (~28M/month).  So... it's not a priority.  But it may get added in the future (e.g. as part of `require('uuid/utils')` or something).

**Comment by jpike88** [comment]
Can this be revisited? Would be handy with tree shaking and stability of uuid standards.

**Comment by ctavan** [comment]
@jpike88 could you elaborate a bit more what you mean with "tree shaking and stability of uuid standards"? And did you try out https://www.npmjs.com/package/uuid-validate ?

**Comment by jpike88** [comment]
tree shaking means that any util exports won't be needlessly packaged, preserving low bundle size.

uuid standards don't change, so once the utilities are set up they won't require any extra maintenance.

yes, I'm aware of the other package and tried it out... but it might even be important to even encourage the use of a validator along with your generation tools, as UUIDs are often used as arguments in HTTP calls.

**Comment by broofa** [comment]
> tree shaking means that any util exports won't be needlessly packaged

Tree shaking only works with ES modules.  It's not really a thing for commonJS / vanilla JS code.

> uuid standards don't change, so once the utilities are set up they won't require any extra maintenance.

How this relevant?

> yes, I'm aware of the other package and tried it out...

Why didn't it work for you?

> but it might even be important to even encourage the use of a validator along with your generation tools, as UUIDs are often used as arguments in HTTP calls.

The numbers suggest validation is not important to most users, not by several orders of magnitude.

![image](https://user-images.githubusercontent.com/164050/59512896-8fb41000-8e6e-11e9-9497-57d8c0af93d9.png)
![image](https://user-images.githubusercontent.com/164050/59512915-9b9fd200-8e6e-11e9-806e-275ff910ed9f.png)
