### ISSUE TITLE
Parse uuid

### ISSUE THREAD

**Issue by xaviergxf** [kelektiv/node-uuid#250]
Hi,

   I know this was a decision you took to remove the parse method, but can you review your decision and perhaps create a parse.js file with its contents. In my project (spa angular app) i was using your old library node-uuid to parse and compare, i'm trying to upgrade to npm package uuid with i've added https://github.com/zefferus/uuid-parse for parsing purposes but i'm running into the following problem:
https://github.com/zefferus/uuid-parse/issues/3
  I just wanted two simple functions: generate and compare uuid and now i have to use 2 libraries which uuid-parse unfortunately doesn't work with ie 11. Can you please review your decision to remove this function?

Thanks a lot,
Xavier

**Comment by broofa** [comment]
My apologies for taking so long to respond to this.  This module is fairly mature so I tend to maintain it in fits and spurts.

I agree you have a legitimate gripe with `uuid-parse`, however I think the right solution would be to push for a fix in that module.  I'm afraid parsing and validation simply [aren't in enough demand](https://github.com/kelektiv/node-uuid/issues/261#issuecomment-400316167) to warrant inclusion here.  If that IE11 issue is really a concern, I'd suggest opening a PR and arguing your case further.  :-/
