### ISSUE TITLE
using  rng-browser.js: global is not defined (3.1.0)

### ISSUE THREAD

**Issue by cecemel** [kelektiv/node-uuid#252]
Hi, 

when using the library in chrome/firefox, I get: 

`ReferenceError: global is not defined`

Seems this line is an issue: 
https://github.com/kelektiv/node-uuid/blob/v3.1.0/lib/rng-browser.js#L7

It seems, this should be the line: https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto

Or am I mistaken?

**Comment by broofa** [comment]
Yeah, sorry about this.  #247 fixes this (I believe).  There are a handful of PRs waiting for approval before we push out a new release.

ping @defunctzombie @vvo - Can one/both of you guys take a pass on the open PRs and approve/comment.  We need to get a new version out.

**Comment by cecemel** [comment]
thx

**Comment by vvo** [comment]
I did some review, what I could, all good @broofa

**Comment by broofa** [comment]
Fixed in v3.2.1 (published)
