### ISSUE TITLE
AMD requireJs support

### ISSUE THREAD

**Issue by mafar** [kelektiv/node-uuid#255]
Please consider supporting for amd requrieJs usage as well.

**Comment by broofa** [comment]
Not to be flip, but this is what packaging tools are for.

If you look back through the commit history, you'll see this module used to jump through all the usual hoops needed to support AMD, Require.js, and Common.js, as well as non-module environments.  The code for which produced an unending stream of bug reports.  Dropping that code was one of the better decisions @defunctzombie made when he forked this repo from my original codebase.

All that said, I'm always reluctant to reject a feature request out of hand without more information.  You're welcome to put up a PR with proposed changes.  Just be aware of the above history, and what that means for the odds of your PR getting accepted.
