### ISSUE TITLE
uuid.v4() has issues in the release 3.2.0

### ISSUE THREAD

**Issue by Kiran-N** [kelektiv/node-uuid#259]
TypeError: Illegal invocation
    at e.exports (rng-browser.js:13)
    at Object.r (v4.js:13)

**Comment by vrch** [comment]
This has already been handled, see
https://github.com/kelektiv/node-uuid/issues/256
https://github.com/kelektiv/node-uuid/pull/257

Use version 3.2.1 instead of 3.2.0

**Comment by Kiran-N** [comment]
just saw that https://github.com/kelektiv/node-uuid/commit/262a8ea8db3906762d967d0d09afa46ee8bfb96e this fixed it.
