### ISSUE TITLE
Validating

### ISSUE THREAD

**Issue by igordeoliveirasa** [kelektiv/node-uuid#261]
Is there any way to validate a uuid value?

**Comment by zackyjack** [comment]
maybe you can use [uuid-validate](https://www.npmjs.com/package/uuid-validate) or [is-uuid](https://www.npmjs.com/package/is-uuid).

hopefully can help.

**Comment by robwierzbowski** [comment]
We use uuid-validate. It's a great companion library.

**Comment by broofa** [comment]
Closing this out for now.  While I'm open to the idea of adding support for parsing and validation now that it wouldn't affect the internal dependencies, the download stats for https://github.com/zefferus/uuid-parse (~5K downloads/week) and https://github.com/mixer/uuid-validate (13K/wk) suggest it's just not worth it.  Combined, those modules are used ~0.25% as often as `uuid` (8M/wk).  That's just not enough to merit rolling them into this module.

As always, I'm open to arguments to the contrary.
