### ISSUE TITLE
duplicates?

### ISSUE THREAD

**Issue by barbalex** [kelektiv/node-uuid#262]
Why does this code:

testUuid.js:
```js
const uuidv1 = require('uuid/v1')

const array = [1, 2, 3]
array.forEach(i => {
  const uuid = uuidv1()
  console.log(i)
  console.log(uuid)
})
```

produce this output:

```bash
alexa@DESKTOP-6C4V66Q C:\Users\alexa\ae_import  
> node src/testUuid.js                          
1                                               
8fa29120-0abe-11e8-b67b-c7f63e34d731            
2                                               
8fa3a290-0abe-11e8-b67b-c7f63e34d731            
3                                               
8fa3c9a0-0abe-11e8-b67b-c7f63e34d731
```

I noticed this happens often in my project.

This question was asked a while ago (https://github.com/kelektiv/node-uuid/issues/74#issuecomment-222780669) and remained unanswered. But as it was asked on a closed issue so I thought I'd reopen an issue for it.

**Comment by barbalex** [comment]
Well, I actually realized that the generated uuid's are not same.

I guess it is time to go to bed.

**Comment by vvo** [comment]
> Well, I actually realized that the generated uuid's are not same.

This would have tricked me too

**Comment by dm-grinko** [comment]
I was here
