### ISSUE TITLE
uuidV5 in lambda not generating unique id

### ISSUE THREAD

**Issue by sthang** [kelektiv/node-uuid#263]
Context: We have a Nodejs API server running in Lambda. It will create userId cookies and send it back in response. The value of the cookie should be unique and random so we used 'uuidv5'. 

Problem: Here's the sample code:

const uuidV5 = require('uuid/v5');
 userCookie.id = uuidV5('example.com',uuidV5.DNS); 

When we test this code it generates once and all consecutive requests the same id is being used. We tried from different browsers and computers. So we started using v4 and it works as expected. 

Is there anything in the V5 that would cause this issue in Lambda services?

**Comment by broofa** [comment]
That is expected behavior.  v3 and v5 uuids are are constructed deterministically, by hashing the name and namespace arguments.  For any given name+namespace argument, you will always get the same uuid.

**Comment by sthang** [comment]
Sorry I thought by calling uuidV5 with a present domainName and DNS we would random IDs within that values. I did not realize UUIDv5 will remain constant for domainName and DNS combinations.

**Comment by broofa** [comment]
Personally, I've never needed namespaced (v3 or v5) uuids, but there are certainly cases where they're useful.  The main characteristics of a namespaced uuid is that 1) it's deterministically generated and 2) it's not easily reversed.

https://en.gravatar.com/site/implement/images/ is an example of a system where something like this might be useful (except they don't use UUIDs).  There, the image URL is a hash of the user's email (i.e. deterministically generated, so there's no need to maintain a database that maps email -> uuid), and not easily reversed, so the email address remains private.  Gravatar's [simple hash algorithm](https://en.gravatar.com/site/implement/hash/) could just as easily be `uuidV5(user_email, GRAVATAR_NAMESPACE)`. (Where GRAVATAR_NAMESPACE is some constant uuid they've chosen.)
