### ISSUE TITLE
adding namespaces for v5

### ISSUE THREAD

**Issue by benjamine** [kelektiv/node-uuid#266]
it seems this lib is missing 2 namespaces here (OID and X500):

https://github.com/securityscorecard/orion/blob/4fd1fb29d8d6312fd7065cfc1a2887f818a3f1dc/src/main/scala/com/securityscorecard/datapipe/orion/utils/UUIDType5.java#L18

would you accept a PR adding them here?

**Comment by broofa** [comment]
See https://github.com/kelektiv/node-uuid/pull/205

tl;dr: OID is obscure, X500 is obsolete.
