### ISSUE TITLE
UUID generating "----" during tests

### ISSUE THREAD

**Issue by Pyrathar** [kelektiv/node-uuid#286]
During tests upon calling the scripts it will generate "----" as an UUID, this however does not happen when i run the actually scripts itself.

I am running Node8 and the line that invokes UUID is a simple as:
const X = uuid()

**Comment by broofa** [comment]
Pretty sure this an issue @Pyrathar's setup.  If/when an SSCCE is provided I'll reopen and humbly apologize.  😄
