### ISSUE TITLE
v1: Passing values larger than 1 byte in options.node results in invalid uuid string

### ISSUE THREAD

**Issue by CutmanCometh** [kelektiv/node-uuid#292]
try this:
`console.log(uuidv1({options : [1, 2, 3, 4, 5, 256]})`.

You get either "...-...-...-...-0102030405" or "...-...-...-...-0102030405undefined", depending on your console settings.

Same thing with negative numbers.
Same thing if you passing too few bytes.
No error happens if you pass in too many bytes, but it would nice to have that little bit of validation anyway.

**Comment by CutmanCometh** [comment]
I have a fix for this already written. I'm trying to get it pushed up, then I'll submit a pull request.

**Comment by broofa** [comment]
Is your code sample right?  ‘v1()’ options doesn’t support an array of random values. Please see the read me for documentation on that method.

**Comment by JoshWalkerJolt** [comment]
Oh. Duh. Sorry.
`console.log(uuidv1({node : [1, 2, 3, 4, 5, 256]})`.
`node` not `options`.

**Comment by CutmanCometh** [comment]
Oh. Duh. Sorry.
console.log(uuidv1({node : [1, 2, 3, 4, 5, 256]}).
node not options.

**Comment by CutmanCometh** [comment]
The documentation has this example, passing in integers in hex form:
`const v1options = {
  node: [0x01, 0x23, 0x45, 0x67, 0x89, 0xab],
  clockseq: 0x1234,
  msecs: new Date('2011-11-01').getTime(),
  nsecs: 5678
};
uuidv1(v1options);`

Accidentally sending in numbers outside the 0-255 range could result in quirky behavior that would be difficult to debug.

**Comment by CutmanCometh** [comment]
Like I said, I've already written a fix for it. I'll push it up on a branch this evening, when I get off work.

**Comment by CutmanCometh** [comment]
Well. Apparently, I can't push, even to a branch.
