### ISSUE TITLE
Change require statement at README

### ISSUE THREAD

**Issue by pbozzi** [kelektiv/node-uuid#296]
Change require statements at README.md from
```
const uuidvX = require('uuid/vX');
```

to
```
const uuidvX = require('node-uuid');
```

**Comment by broofa** [comment]
From README

> [Deprecation warning: The use of require('uuid') is deprecated and will not be supported after version 3.x of this module. Instead, use require('uuid/[v1|v3|v4|v5]') as shown in the examples below.]
