### ISSUE TITLE
Buffer deprecation warning

### ISSUE THREAD

**Issue by fainashalts** [kelektiv/node-uuid#298]
Hi, for anyone using this package with Node 10+ the following warning appears: 

(node:40553) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

It does appear that Buffer() may be used in the md5 and sha1 libraries, and possibly elsewhere that I didn't see. Is it possible to change these? `new Buffer` was deprecated in node 10. In most cases you can use the `Buffer.from()` methods in the same way as `new Buffer` and avoid the warning (`alloc` and `allocUnsafe` come in to play when initializing a Buffer of a specific size)

**Comment by fainashalts** [comment]
More information/documentation from node: https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/

**Comment by broofa** [comment]
Ran `npm test` with node 10 and 11, and am not seeing this warning.  All code in this module that creates buffers is "smart" about detecting the new api.  E.g. https://github.com/kelektiv/node-uuid/blob/master/lib/md5.js

Closing for now, as I suspect this warning is coming from calling code.  If this is still a problem for you feel free to submit a PR with the fix, though.
