### ISSUE TITLE
uuidv4 generates invalid uuid

### ISSUE THREAD

**Issue by Samueljoli** [kelektiv/node-uuid#301]
**Node version:** `8.9.1-slim`
**Package version:** `3.3.2`

Expected: 
```js
const uuidv4 = require('uuid/v4');

this.id = uuidv4()

console.log(this.id) // => --40-80-
```

I'm running this logic in an [Objection](https://github.com/Vincit/objection.js) model class on a beforeInsert hook. At the moment I've only confirmed that this happens whenever I'm running tests.
**Framework:** `mocha`
**version:** `4.x.x`

**Comment by broofa** [comment]
Is `mocha` or some other utility replacing the `crypto` or `crypto.randomBytes()` function with a shim of some sort?

**Comment by Samueljoli** [comment]
@broofa You hit that right on the head... 👍 I'm going to close this out
