### ISSUE TITLE
Fails in Internet Explorer

### ISSUE THREAD

**Issue by TJonesy** [kelektiv/node-uuid#308]
In internet explorer it crashes because crypto is undefined.

**Comment by broofa** [comment]
[SSCCE](http://sscce.org/)? What version of IE? Stack trace?

**Comment by broofa** [comment]
Closing, as I suspect you're seeing #284 which is fixed in latest.  Make sure you're using most recent `uuid` version and report back here if this is still an issue.

**Comment by TJonesy** [comment]
I am not sure that is the same issue but I will give that a try. Sorry I have not had time yet to make an example. Running in IE11 (or IE9 emulation) it crashes my entire react app with the error Crypto is undefined. Doing `if(window.msCrypto) { window..crypt = window.msCrypto; }` in my main app fixes the issue for me in IE11.

**Comment by broofa** [comment]
Well, there's code to handle the various IE idiosyncracies around crypto so... :-/

https://github.com/kelektiv/node-uuid/blob/master/lib/rng-browser.js#L8-L9
