### ISSUE TITLE
Uniqueness of the Generated id

### ISSUE THREAD

**Issue by kashifaliquazi** [kelektiv/node-uuid#310]
This is not an issue. but better understating can make easier for the end user to implement it.

In the Readme it is mentioned:

Note: The id is generated guaranteed to stay constant for the lifetime of the current JS runtime. (Future versions of this module may use persistent storage mechanisms to extend this guarantee.)

It is confusing to me. 
Can anyone please elaborate what the author is trying to say with a meaningful example(where can this uniqueness fails).

**Comment by broofa** [comment]
Sorry, I can see why you're confused.  There's a bit of a typo there and it's not very clear.

What I was referring to with that comment (which I'll fix momentarily) is that the `node id` ([as defined](https://tools.ietf.org/html/rfc4122#section-4.1.6) in the RFC) is randomly initialized once, at process startup, and then remains for the duration of the process.

For example, if you generate multiple v1 ids w/in the same process like so, they each have the same node id (the last group of digits, in this case, `7ff9d16a1fa1`):
```
$ node
> uuidv1 = require('uuid/v1')
[Function: v1]
> uuidv1()
'39bd3450-5a08-11e9-9490-7ff9d16a1fa1'
> uuidv1()
'3a4290f0-5a08-11e9-9490-7ff9d16a1fa1'
> uuidv1()
'3aaee750-5a08-11e9-9490-7ff9d16a1fa1'
```

But if you create v1 ids in separate processes, e.g. by using the CLI, you'll get a different node id each time (except in the very unlikely case the node is randomly the same):
```
$ bin/uuid
d5ffda74-f42f-43d9-a866-12c6cf943cdf
$ bin/uuid v1
cdc32fb0-5a08-11e9-b122-6111b0a4a537
$ bin/uuid v1
cf4080e0-5a08-11e9-a181-6f67198692b5
```
