### ISSUE TITLE
Release latest Readme to npm

### ISSUE THREAD

**Issue by ctavan** [kelektiv/node-uuid#318]
@broofa please check this thread: https://github.com/gatsbyjs/gatsby/pull/15407#discussion_r300392112

Seems like the current readme on v1 UUIDs on npm is confusing. Could we release a new bugfix release to get the latest README published on npm as well? As far as I can tell from https://github.com/kelektiv/node-uuid/compare/v3.3.2...master it's only documentation and maintenance changes, so bugfix release should be fine.

**Comment by ctavan** [comment]
@broofa may I bring this to your attention again? Would be a pretty low hanging fruit and apparently resolve some confusion (see linked thread above).

**Comment by broofa** [comment]
Published
