### ISSUE TITLE
How can I stub uuid

### ISSUE THREAD

**Issue by avinersan** [kelektiv/node-uuid#322]
How can I stub function uuid v4 if imported like `import * as uuid from 'uuid/v4'`?

**Comment by broofa** [comment]
What do you mean?

**Comment by avinersan** [comment]
If I have a function, let's say getId(), that just returns 'prefix' +
uuid();
In order to unit test this function I would like to mock dependencies which
in this case would be to fake the uuid ( using sinon for example or other
library) to return a string that I can test.

Because the v4 function is exported as a default
(module.exports=function....) there seems to not be a way to mock it except
something like proxyquire which is a headache (it mocks the whole module).

**Comment by broofa** [comment]
Got it.  I'm afraid I don't have a simple answer for you.  proxyquire is probably your best bet (I haven't used it though, so can't say for sure.)

**Comment by broofa** [comment]
I hate to suggest this, but the deprecated api `require('uuid').v4` is still available.  You could change your import to `import {v4} from uuid`, if that would help.  But... yeah, that api will go away eventually.

**Comment by avinersan** [comment]
I was also thinking of that but saw that it is deprecated. I'll wrap all usages in my own module though to avoid this. 

Thank you for the quick response

**Comment by ctavan** [comment]
@avinersan I recently saw the uuid library mocked in some Microsoft Azure stuff: https://github.com/microsoft/azure-pipelines-tasks/blob/886ae75b5b09c6fee7072c18fff9fab26e14b768/Tasks/PublishTestResultsV2/Tests/TestSetup.ts#L46-L49

It might be pretty specific tooling that Microsoft has set up over there. Maybe still worth a look for inspiration?

**Comment by avinersan** [comment]
Thanks @ctavan for the info. I checked the code and it uses mockery underneath which hooks into the require module loader similar to proxyquire which I wanted to avoid.

**Comment by ctavan** [comment]
Sorry to hear @avinersan, but thanks for sharing the insight!

**Comment by rooby** [comment]
You can do this with Jasmine:
```
import * as uuid from 'uuid';
...
spyOnProperty(uuid, 'v4').and.returnValue(() => 'f3b3a923-61b3-4d6f-9a7e-632061825358');
```

**Comment by djungowski** [comment]
> You can do this with Jasmine:
> 
> ```
> import * as uuid from 'uuid';
> ...
> spyOnProperty(uuid, 'v4').and.returnValue(() => 'f3b3a923-61b3-4d6f-9a7e-632061825358');
> ```

Neither `spyOnProperty` nor `spyOn` work as they produce the errors
```
Error: <spyOnProperty> : v4 is not declared configurable
```
or
```
Error: <spyOn> : v4 is not declared writable or has no setter
```
respectively.

This is kinda annoying, I have to say.

**Comment by djungowski** [comment]
> You can do this with Jasmine:
> 
> ```
> import * as uuid from 'uuid';
> ...
> spyOnProperty(uuid, 'v4').and.returnValue(() => 'f3b3a923-61b3-4d6f-9a7e-632061825358');
> ```

This does not work anymore, since it will produce the error
```
Error: <spyOnProperty> : v4 is not declared configurable
```

The same applies for `spyOn`. The way to go is to write some kind of service for your application that uses v4 that you can then mock
