### ISSUE TITLE
Add an Ethereum name or address to package.json

### ISSUE THREAD

**Issue by lastmjs** [kelektiv/node-uuid#325]
I would like to see an Ethereum name or address added to the ethereum field of the package.json file. This will allow consumers of the project to know a cannonical address to send funds to. For example, I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have an Ethereum address in their package.json file. 

Having an Ethereum address would allow many types of cryptocurrencies to be donated, including stablecoins pegged to USD, like USDC or DAI. Essentially it is another payment network like PayPal, but open and decentralized like the internet. Getting an address is relatively straightforward through something like MetaMask or Coinbase. You could also generate one on your own.

**Comment by broofa** [comment]
Quit spamming popular repositories.

![image](https://user-images.githubusercontent.com/164050/64076808-642b0f80-cc7e-11e9-8fc4-9e564dd6fb15.png)
