### ISSUE TITLE
v3.3.3 throws an error about assigning a read only property "exports" to object

### ISSUE THREAD

**Issue by emmenko** [kelektiv/node-uuid#326]
After upgrading to `v3.3.3` we are getting these errors (browser app):

<img width="793" alt="image" src="https://user-images.githubusercontent.com/1110551/63919093-55561a00-ca3e-11e9-960a-710dc9b51832.png">

**Comment by ctavan** [comment]
@emmenko what was the last working version for you? The `3.3.3` release was documentation only, nothing about the source code itself changed. So the error you're seeing comes pretty surprising.

Could you also please provide more information on the build environment (webpack? babel?) that you're using to bundle the browser app and ideally more detailed steps to reproduce the issue?

**Comment by emmenko** [comment]
Sure, the `v3.3.2` works fine.

However, I just try again `v3.3.3` and used yarn's `resolutions` field to pin the version to `3.3.3` and things seem to work fine again...somehow having 2 different versions caused an error 🙃

Sorry for the trouble
