### ISSUE TITLE
feature request: CDN (again)

### ISSUE THREAD

**Issue by cekvenich** [kelektiv/node-uuid#333]
The unstable CDN was removed.
If we can just have the compiled es5 .js file in the repo, then any CDN would work after an npm publish or github release. CDN's use npm or github release as source.
Then we users of the lib can pick a CDN we like.

So: please include a compiled es5 .js file in the repo; and release either npm publish or github publish please.

**Comment by ctavan** [comment]
@cekvenich have you seen https://github.com/kelektiv/node-uuid/issues/302#issuecomment-524827935? Does this not work for you?

**Comment by cekvenich** [comment]
it does, thx
