### ISSUE TITLE
Rename repository to uuid

### ISSUE THREAD

**Issue by ctavan** [kelektiv/node-uuid#336]
Given that this module is cross-platform (node + browser) and that the npm module has been renamed to `uuid` long time ago, I suggest renaming this repository to `kelektiv/uuid` as well.

Since [GitHub will keep redirects](https://help.github.com/en/articles/renaming-a-repository) from the old name to the new name this should not cause any real trouble.

@broofa @defunctzombie opinions?

**Comment by broofa** [comment]
Works for me.

**Comment by broofa** [comment]
Moving to #338
