### ISSUE TITLE
Use WebCrypto for SHA1 hashing in the browser

### ISSUE THREAD

**Issue by ctavan** [kelektiv/node-uuid#339]
Now that there is https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest it could be used instead of the custom browser code if available.

**Comment by broofa** [comment]
According to that page SHA-1 isn't supported on Edge yet... which raises the question of, "_what's our platform support policy?_"  It would probably be a good idea to formalize that, and do so in a way that lets it be versioned alongside the codebase.

**Comment by ctavan** [comment]
@broofa this was more of a "note to self" because I stumbled upon it, I don't necessarily want to tackle this immediately.

However I extracted your platform support matrix suggestion into #340, I wanted to add some browser tests anyways…

**Comment by ctavan** [comment]
I just realized that `SubtleCrypto.digest` returns a Promis, so unless we would want to change the API of `uuid` to be async as well, this doesn't seem to be an option anyways.
