### ISSUE TITLE
Support base64 or 62

### ISSUE THREAD

**Issue by revington** [kelektiv/node-uuid#47]
It would be great to have uuid's in base62/64 format for docs, urls, or for couchdb _id

**Comment by dmarcelino** [comment]
If anyone is interested in generating base62 UUIDs, I've created [uuid-base62](https://github.com/dmarcelino/uuid-base62) for that purpose. It also exposes `node-uuid` for convenience.

**Comment by G7495x** [comment]
It is 2021. I guess it may be time to reconsider this once again...? I see two major formats - **Base64** and **Base64URL**. Please consider... I have been using helper functions for too long already...

**Comment by ctavan** [comment]
Please see https://github.com/uuidjs/uuid/issues/47#issuecomment-8197007

The goal of this library is to implement the [RFC4122](https://datatracker.ietf.org/doc/html/rfc4122) standard, nothing more, nothing less.
