### ISSUE TITLE
Types are nowhere to be found in the library after installation despite the promise they are included

### ISSUE THREAD

**Issue by stopsopa** [kelektiv/node-uuid#797]
### Feature description

<img width="403" alt="image" src="https://github.com/user-attachments/assets/fd0c6fd1-89f2-4c1b-9a17-0745c27a79ec">
<img width="495" alt="image" src="https://github.com/user-attachments/assets/ea04d7f0-bb24-4354-9952-841b9ca1392a">
<img width="498" alt="image" src="https://github.com/user-attachments/assets/64275f87-a475-4bd8-bdb7-77be54045147">
<img width="463" alt="image" src="https://github.com/user-attachments/assets/884fc8c2-10c5-456b-ba0d-8ff63b42556b">
<img width="496" alt="image" src="https://github.com/user-attachments/assets/7ea2a40d-8291-46ca-9ab9-0b3e6d817b01">

And nothing found in dependencies https://github.com/uuidjs/uuid/blob/v11.0.0-0/package.json

**Comment by broofa** [comment]
You have an older version of `uuid` installed.  Types are only available as of version 11 (currently in prerelease).

`npm install uuid@beta` should get you sorted.

**Comment by stopsopa** [comment]
Ah, you are right
