### ISSUE TITLE
node-uuid will generate unique ids across a node js cluster ?

### ISSUE THREAD

**Issue by BinitaBharati** [kelektiv/node-uuid#82]
UUIDs conceptually are supposed to generate unique ids at any point of space and time.  So, does this module also guarantee the same across a nodejs cluster ?

Thanks

**Comment by enrichz** [comment]
+1 for the awesome explanation, thanks you.

**Comment by nodesocket** [comment]
Could we perhaps replace the MAC address with the node.js pid? Wouldn't that help with clusters?

For example replace MAC address with `process.pid` and pad the rest with random.

**Comment by thosil** [comment]
@nodesocket not sure it's a good idea, if you run node.js inside a docker its pid will always be 1.

**Comment by tmorehouse** [comment]
Onecould grab the first non 'internal' interface's IPV4 address from `os.networkInterfaces()`, use that as the first 4 butes of the node ID, and then use the `process.pid` to generate teh last two bytes:
~~~~~~~~
var addr = '1.2.3.4.'; // say from os.networkInterfaces().eth0[0]
var pid = process.pid;
var nodeid = [
    ...addr.split('.').map(function(n){return parseInt(n,10)}),
     (pid >>> 8) & 0xff,
     pid & 0xff
];
// nodeid is now something like [ 0x01, 0x02, 0x03, 0x04, 0x56, 0x78]
var u = uuid.v1({node:nodeid});
~~~~~~~~

**Comment by broofa** [comment]
@tmorehouse IP-based UUIDs introduces the requirement that you can't have two systems on LANs that assign similar IP ranges.

**Comment by tmorehouse** [comment]
Yeah, this would only work for systems that have unique IP's across instances, and across `fork()`ed processes on those instances

But the nice thing about `node-uuid` is that you can assign your own 6 byte node ID value any way you like, assuming your are only using these UUIDs (V1) within your application (i.e. no other UUID generation is used).

**Comment by murphman300** [comment]
Hello,

Simple question, using the uuid.v1 method, is it possible to re-create a uuid if you supply the `options` fields?

**Comment by broofa** [comment]
@murphman300 https://github.com/kelektiv/node-uuid/blob/master/test/test.js#L77
