### ISSUE TITLE
Browserify is shimming require('crypto') and Buffer

### ISSUE THREAD

**Issue by speigg** [kelektiv/node-uuid#84]
The following commit seems like it was supposed to prevent browserify from shimming 'crypto' and Buffer:
319dc6e2e75f8ff57

But it doesn't seem to be working (at least with the latest version of browserify)

**Comment by coolaj86** [comment]
Is this still an issue?

**Comment by rmarscher** [comment]
This is an issue with the bundler and not necessarily node-uuid. However, node-uuid could solve it by having an alternate entry point when the package is required in a browser context by using the "browser" key in package.json. See https://github.com/crypto-browserify/randombytes for an example on how to do that. The bundlers aren't smart enough to see that `'crypto'` an `Buffer` are only used conditionally if the `window` global is defined.

With the current version of node-uuid, you can prevent from bloating your bundle with browserify or other bundlers by configuring them bundler to ignore or shim `'crypto'` and `'Buffer'` to empty objects. The conditionals in node-uuid don't use them if the `window` global exists anyway. Modern browsers offer `window.crypto` or `window.msCrypto` which node-uuid will use instead and then fall back to a built-in random number generator if the browser doesn't supply a crypto library.

In browserify, you can use `--ignore` or `b.ignore()` to ignore the `'crypto'` and `'buffer'` packages. I believe webpack has an IgnorePlugin that works similarly.
