### ISSUE TITLE
Add isValid methods

### ISSUE THREAD

**Issue by NatWeiss** [kelektiv/node-uuid#85]
Hi Broofa, nice project here. ;) Just a suggestion. It would be nice if there was a method sort of like:

```
nodeUuid.isV4(someUuidString);
```

That way it would be easy to know if a string is a valid UUID v4. Right now, I have to resort to something janky like this:

```
if (!uuid || uuid.length < 32 || uuid.indexOf("-") < 0) {
    uuid = nodeUuid.v4();
}
```

**Comment by tjconcept** [comment]
+1

**Comment by marbemac** [comment]
For those wondering how to validate a UUID v4, the regex looks like this (in JS, but generally applicable):

```js
var id = "the id to test";
/^[a-z0-9]{8}-[a-z0-9]{4}-4[a-z0-9]{3}-[a-z0-9]{4}-[a-z0-9]{12}$/.test(id)
```

**Comment by tracker1** [comment]
@NatWeiss @tjconcept might want to take a look at [validator](https://www.npmjs.com/package/validator), which will give you a lot more than just UUID validation.

**Comment by tjconcept** [comment]
@tracker1 "a lot more" is a bad thing in my book ;-)
Thanks @marbemac, I still think it would a nice addition to this library though.

**Comment by marbemac** [comment]
@tjconcept I agree, would be a nice addition to the library.

**Comment by tracker1** [comment]
@tjconcept @marbemac Although I understand the concern... I'm assuming you have to validate more than just UUIDs in your application... that being the case a common abstract for validation is probably better than a custom one for each type of data.

**Comment by Cyber-ITConfig** [comment]
Yeah, I like this idea!

**Comment by tjconcept** [comment]
> I'm assuming you have to validate more than just UUIDs in your application...

No I don't :)

**Comment by vdininski** [comment]
:+1:

**Comment by vdininski** [comment]
+1

**Comment by jtemplet** [comment]
I also think this would be a great idea and I also like the syntax suggested above:

nodeUuid.isValid(input)
// returns boolean

I'd volunteer to add this feature

**Comment by jiayihu** [comment]
+1
Is this repo still active? I'd like also to add this feature but the pending Pull Requests are not reassuring.

**Comment by karlbateman** [comment]
This is an old issue, but would be a great feature :+1:
