### ISSUE TITLE
fix docs or implementation as uuid.parse return Array instead of Buffer

### ISSUE THREAD

**Issue by Delagen** [kelektiv/node-uuid#97]
```
var bytes = uuid.parse('797ff043-11eb-11e1-80d6-510998755d10'); // -> <Buffer 79 7f f0 43 11 eb 11 e1 80 d6 51 09 98 75 5d 10>
```

this returns [79,127,...,10]

**Comment by coolaj86** [comment]
What platform were you running this on? Browser? Node? Browserify / PhantomJS?

**Comment by lillem4n** [comment]
I just came across this aswell, running node v4.2.6.
The .parse() for me returns an array of bytes, not a buffer.
